### ISSUE TITLE
Isn't process.env object and not array?

### ISSUE THREAD

**Issue by AlexandruSimandi** [WebDollar/Node-WebDollar#1]
This is unreachable code since process.env is an object.

https://github.com/WebDollar/Node-WebDollar/blob/618a641acc24c6b693336863202678548036e76f/src/index.js#L13-L16

**Comment by AlexandruSimandi** [comment]
I also recommend using [dotenv](https://www.npmjs.com/package/dotenv) since it eases deployments and environment control.

**Comment by AlexandruSimandi** [comment]
```
for (let key in process.env) 
    if (typeof process.env[key]  === 'string') 
        if (process.env[key].toLowerCase() === 'true') process.env[key] = true; 
        else if (process.env[key].toLowerCase() === 'false') process.env[key] = false; 
```

**Comment by ibudisteanu** [comment]
Hi Alexandru, 

@AlexandruSimandi thanks for reporting this issue.  The reason why I wrote that piece of code is that in the package.json, we have some in-line scripts that use TRUE and FALSE and strings input, while using the Value "True" and  "False" as strings is quite hard in the code.

Very probably, process.env is indeed an object and not an array, but as I believe you can use for (or forEach) to map an Array, but also an Object. Am I wrong at this?

dotenv package looks interesting. Would you like to integrate the dotenv packages ?

Indeed, if we integrate dotenv, we will remove that piece of code.
