### ISSUE TITLE
/wallets/import API endpoint does not work

### ISSUE THREAD

**Issue by morion4000** [WebDollar/Node-WebDollar#122]
Calls to the `/wallets/import` endpoint fail with `{"result":false,"message":"Address already exists!"}`, regardless of the `privateKey` parameter.

**Comment by morion4000** [comment]
I think this is related to: https://github.com/WebDollar/Node-WebDollar/issues/74

**Comment by kirsanovdm** [comment]
On which wallet can WEBD be displayed?
