### ISSUE TITLE
Express server starts on different ports

### ISSUE THREAD

**Issue by morion4000** [WebDollar/Node-WebDollar#17]
Replication steps:

- run `npm run commands`, select `8`, the express server starts on port `3333`
- run `npm run start_mining`, the express server starts on port `80`

I believe this is inconsistent.

**Comment by ibudisteanu** [comment]
This is not an issue. We may decide to switch all ports to port 80. Port 80 is used because many Internet Providers block non 80 port.

**Comment by IonutAlexandruPanait** [comment]
Non issue
