### ISSUE TITLE
findPendingIdenticalTransaction is not a function

### ISSUE THREAD

**Issue by tomkha** [WebDollar/Node-WebDollar#178]
there is a call of [non-existent function here](https://github.com/WebDollar/Node-WebDollar/blob/master2/src/common/blockchain/interface-blockchain/transactions/protocol/Transactions-Download-Manager.js#L218) hidden by the [empty catch block](https://github.com/WebDollar/Node-WebDollar/blob/master2/src/common/blockchain/interface-blockchain/transactions/protocol/Transactions-Download-Manager.js#L150)

```
TypeError: this.blockchain.transactions.pendingQueue.findPendingIdenticalTransaction is not a function
    at TransactionsDownloadManager._createTransaction
```
findPendingIdenticalTransaction is not declared in TransactionsPendingQueue

**Comment by ibudisteanu** [comment]
Thanks for reporting. Indeed on master2, the function was deleted by mistake. I fixed it.

**Comment by ibudisteanu** [comment]
I believe I have fixed it. In case you encounter the issue again, please open the issue.
