### ISSUE TITLE
Help with the block deserialization off-chain

### ISSUE THREAD

**Issue by ader1990** [WebDollar/Node-WebDollar#19]
Hello,

I do not want to run the WebDollar code, as I would like to refactor this part, as this code is core to what happens in the blockchain and it should be kept as loosely coupled as possible.

 I have run the following and got the attachment data for block01 of webdollar blockchain
>> blockchainDB.get("block0", {attachments: true, include_docs: true}, function (err,doc) {data = doc._attachments.key.data})

Variable data looks like this:
>> data
>>'MDAwMDdlMzAxMzcxMWJjMTI2YTg3MDhhMzI0NDcyZmRmY2Y2ODU1Y2VmMWY5NzliMGRmNDM0NzVjOTU2OGUzMzAwMDBlNzI0MDAwMTczMWQ0NmMxMzFlYjZkZDQ2NjdhOTZiZGMyN2JhZjkyMjNiZWM3MmMzNDY4ZGZiNmJhNTJjNDYwZTc2NDIzYTQwMDAwMDQ0NzZjMWQzNTViMDMyMDU0MTIyMDQ4MDRlNDI3ZjlhNTZkZTE1ZjEwZjBjODBmYzUzMGZlY2RlOWE0OGFlNmFlZGU4NjFlOTkwM2U1NDIyZjdjMTExMzU4MDMyZGZlNmNhMzdhYWQ4YmRkNWRmNmUwZTI3NjEzNTlkMzBhODI3NTA1OGUyOTlmY2MwMzgxNTM0NTQ1ZjU1Y2Y0M2U0MTk4M2Y1ZDRjOTQ1NjAwMDAwMDAwMGExY2ZjZWIyMTVhZWFjNDZjMGI3ZWVhMGQ1ZGE5ZGVmZDkyN2UyNDUwNGI3NTdlNmMzZDM3MDI4NTNjOWM5OTAxMDAwMDAxNzMxZDQ2YzEzMWViNmRkNDY2N2E5NmJkYzI3YmFmOTIyM2JlYzcyYzM0NjhkZmI2YmE1MmM0NjBlNzY0MjNhNA=='

I would like now to deserialize it using the minimum noncluttered nodejs code and obtain the timestamp and previous hash, for example.
Got the code from: https://github.com/WebDollar/Node-WebDollar/blob/4aadea24d7abcac91f3e1438f89162c656aa76d2/src/common/utils/Serialization.js#L100

function deserializeNumber(buffer){

        if(buffer.length === 1) return buffer[0]; else

        if (buffer.length === 2) return buffer[1] | (buffer[0] << 8); else

        if (buffer.length === 3) return buffer[2] | (buffer[1] << 8) | (buffer[0] << 16); else

        if (buffer.length === 4) return buffer[3] | (buffer[2] << 8) | (buffer[1] << 16) | (buffer[0] << 24); else

        if (buffer.length === 6) return buffer[5] | (buffer[4] << 8) | (buffer[3] << 16) | (buffer[2] << 24) | (buffer[1] << 32) | (buffer[0] << 40);
}

function substr(buffer, index, count){

        if (count === undefined)
            count = buffer.length;

        let length = Math.min(index + count, buffer.length);

        if (length-index <= 0)
            throw {message: "length-index <= 0...", buffer: buffer.toString("hex"), index:index, length:length, count: count};

        let buf = new Buffer(length-index);
        buffer.copy(buf, 0, index, length);

        return buf;
}

# And now I would like to know if I am doing stuff right to get the previousHash and timestamp

>> buffer = Buffer.from(data, 'base64')

According to https://github.com/WebDollar/Node-WebDollar/blob/acdd19a5de2d968b2dd2506f9285e8b2229bec98/src/common/blockchain/interface-blockchain/blocks/Interface-Blockchain-Block.js#L293
hashPrev should be at an offset of BLOCKCHAIN.BLOCKS_POW_LENGTH + NONCE + 2

I got a value but it is definitely not the one I am looking for:
> substr(buffer, 0 + 32 + 4 +2, 32).toString("hex")
> '3563656631663937396230646634333437356339353638653333303030306537'

I also get a very bad timestamp:
> deserializeNumber(substr(buffer, 0 + 32 + 4 +2+32, 4))
842281008

Any help would be appreciated.

Thanks.

**Comment by ibudisteanu** [comment]
Try to extract the first data from the Block raw bytes, then proceed to extract the 2nd data, and 3rd and so on. In case you can't extract the first data, then probably you don't have the block raw bytes or in the correct format.

**Comment by ader1990** [comment]
> substr(buffer, 0, 32).toString("hex")
'3030303037653330313337313162633132366138373038613332343437326664'

The problem is that I cannot check if this is okay or not unless I ask someone who can actually confirm it.

**Comment by ibudisteanu** [comment]
This is what I got from interrogating the `this.blocks[0].serializeBlock().toString("hex")`

00007e3013711bc126a8708a324472fdfcf6855cef1f979b0df43475c9568e330000e7240001731d46c131eb6dd4667a96bdc27baf9223bec72c3468dfb6ba52c460e76423a4000004476c1d355b03205412204804e427f9a56de15f10f0c80fc530fecde9a48ae6aede861e9903e5422f7c111358032dfe6ca37aad8bdd5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c9456000000000a1cfceb215aeac46c0b7eea0d5da9defd927e24504b757e6c3d3702853c9c9901000001731d46c131eb6dd4667a96bdc27baf9223bec72c3468dfb6ba52c460e76423a4

![image](https://user-images.githubusercontent.com/17750489/39638439-daaecca6-4fce-11e8-89a5-b902cb720585.png)

**Comment by ibudisteanu** [comment]
block[1] `

`000125988a04e701c324eaa43798751e24422a8c65a3fc2fa78d5dd8d81d6cb600003c26000100007e3013711bc126a8708a324472fdfcf6855cef1f979b0df43475c9568e3300000472920ffd31f9752f90a0bd4c9fba25790b5340d7900b0438273a76b834b9f17856bd87b88551446a84650bdb7525ec27326e55ffd85df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c945600000000229cba7cd7926a980ddae11625db7a7a5e0f5a86267d44ab1689f140cd7a4b7303000001731d46c131eb6dd4667a96bdc27baf9223bec72c3468dfb6ba52c460e76423a400000200007e3013711bc126a8708a324472fdfcf6855cef1f979b0df43475c9568e33000000`

![image](https://user-images.githubusercontent.com/17750489/39638507-13e83ebc-4fcf-11e8-9804-f4c6ea6e33e4.png)

**Comment by ader1990** [comment]
Perfect,  it is the same thing if I do:
atob(Buffer.from(data, 'base64'))

Now, what is a valid hashPrev in hexa for the block[0] or the timestamp?

**Comment by ader1990** [comment]
The timestamp that I got following the code from: 
https://github.com/WebDollar/Node-WebDollar/blob/acdd19a5de2d968b2dd2506f9285e8b2229bec98/src/common/blockchain/interface-blockchain/blocks/Interface-Blockchain-Block.js#L309

is: deserializeNumber(substr(buffer, 0 + 32 + 4 +2+32, 4))
842281008

which is not the same.

This means that either I am doing something wrong (which I do not know), either the code from the repo is wrong.

**Comment by ibudisteanu** [comment]
Your timestamp is for a date in the year of 1997.

I have uploaded you encoded block and decoded block. Try to obtain the values step by step, decoding hash, nonce, version, hashPrev and then the timestamp. Try to extract the current hash.  Check the first image  I have uploaded to see the data. 

Be sure you have the same data as it was posted by me above.

**Comment by ibudisteanu** [comment]
my timestamp is offset with by substracting the Genesis timestamp. You can see the real value in the first screenshot i have uploaded.

**Comment by ibudisteanu** [comment]
Moreover, 1095 is the 0x447. So you can see that I have spotted 0x447 in my hex data

00007e3013711bc126a8708a324472fdfcf6855cef1f979b0df43475c9568e330000e7240001731d46c131eb6dd4667a96bdc27baf9223bec72c3468dfb6ba52c460e76423a4**00000447**6c1d355b03205412204804e427f9a56de15f10f0c80fc530fecde9a48ae6aede861e9903e5422f7c111358032dfe6ca37aad8bdd5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c9456000000000a1cfceb215aeac46c0b7eea0d5da9defd927e24504b757e6c3d3702853c9c9901000001731d46c131eb6dd4667a96bdc27baf9223bec72c3468dfb6ba52c460e76423a4

**Comment by ader1990** [comment]
I told you already the encoded/decoded blocks are okay, I want to know how you extract the timestamp 1095 from that, as the code from the repo does not extract correctly.

**Comment by ader1990** [comment]
Basically, what is the math behind choosing for the timestamp an offset? And what are the steps using the primitives from the repo like substring or deserializeNumber and get you to the value: 1095?

**Comment by ibudisteanu** [comment]
it is simple. I use byte operations.

...60e76423a4**00000447**6c1d355b032...

I extract the bytes, you should get a buffer of 00 00 04 47, then I convert this buffer of 4 bytes into a Number and you will get the 1095 lucky number. Regarding your question, why I have substracted Genesis timestamp as an offset, with the only purpose that all timestamps must be higher than Genesis Timestamp by this way, I am partially solving the Javascript https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by ibudisteanu** [comment]
The genesis timestamp was set as an appropriate number to the Unix timestamp when I was preparing the new hard fork for main net.

**Comment by ader1990** [comment]
The question is from where do I know the offset? this is not documented and what is the math behind finding it?

**Comment by ader1990** [comment]
I am asking a simple thing, a piece of code that gets you from this "00007..a4" string to the timestamp.

**Comment by ibudisteanu** [comment]
deserializeBlock(buffer,, offset){

        if (!Buffer.isBuffer(buffer))
            if (typeof buffer === "string")
                buffer = new Buffer(buffer, "hex");

        if (offset === undefined) offset = 0;

        if ( (buffer.length - offset) > consts.SETTINGS.PARAMS.MAX_SIZE.BLOCKS_MAX_SIZE_BYTES )
            throw {message: "Block Size is bigger than the MAX_SIZE.BLOCKS_MAX_SIZE_BYTES", bufferLength: buffer.length };

        try {

            this.hash = BufferExtended.substr(buffer, offset, consts.BLOCKCHAIN.BLOCKS_POW_LENGTH);
            offset += consts.BLOCKCHAIN.BLOCKS_POW_LENGTH;

            this.nonce = Serialization.deserializeNumber( BufferExtended.substr(buffer, offset, consts.BLOCKCHAIN.BLOCKS_NONCE) );
            offset += consts.BLOCKCHAIN.BLOCKS_NONCE;



            this.version = Serialization.deserializeNumber( BufferExtended.substr(buffer, offset, 2) );
            offset += 2;


            this.hashPrev = BufferExtended.substr(buffer, offset, consts.BLOCKCHAIN.BLOCKS_POW_LENGTH);
            offset += consts.BLOCKCHAIN.BLOCKS_POW_LENGTH;


            this.timeStamp = Serialization.deserializeNumber( BufferExtended.substr(buffer, offset, 4) );
            offset += 4;

extracted from the code.

**Comment by ader1990** [comment]
I found the issue I had in my code:
I should have written:
>>buffer=Buffer.from(atob1(Buffer.from(data, 'base64')), "hex")

instead of:
>> buffer=Buffer(atob1(Buffer.from(data, 'base64')), "hex")
