### ISSUE TITLE
PouchDB freezes in Terminal (backbone) on Unix

### ISSUE THREAD

**Issue by ibudisteanu** [WebDollar/Node-WebDollar#2]
When I run `npm run start_mining` in Terminal tested on Unix

The Wallet `loadAddresses` freezes and never gets a resolved Promise. It always shows me the error message in terminal from the 10 second timeout.

```
            //timeout, max 10 seconds to load the database
            setTimeout(()=>{
                console.log(colors.red("LOAD ADDRESSES FROZE AND FAILED !!"));
                resolve(false);
            }, 10000);

            let buffer = await this.db.get(this.walletFileName);        // never gets resolved
```

Any Idea? @s1lviu  @opreacosmind 

![image](https://user-images.githubusercontent.com/17750489/34638883-d51235f6-f2dd-11e7-95ef-a32a47536862.png)

LE: In Browser it works perfectly!!!

**Comment by ibudisteanu** [comment]
It requres to delete the previous malformed pounchdb database? Initial solution https://github.com/WebDollar/Node-WebDollar/commit/755b67e601567e8f3e88d5e0878f386a21a39911

**Comment by s1lviu** [comment]
@ibudisteanu for me on macOS High Sierra 10.13.2 it's working. 
<img src="https://i.imgur.com/fVXIcVy.png">
Can you give me more details about? Are you sure that you are on Unix and not on Linux?

**Comment by ibudisteanu** [comment]
I know. I think I fixed it in the meanwhile by working on the code. https://github.com/WebDollar/Node-WebDollar/commit/6ffa48fae89c72bd5cb1fa2faadb8ac7a67d08ec https://github.com/WebDollar/Node-WebDollar/commit/5f078a1f15ab1d2d314dd1e144e190aa36aa5337

**Comment by s1lviu** [comment]
Great then!
