### ISSUE TITLE
Hash Rate on Nodes

### ISSUE THREAD

**Issue by rentodi1** [WebDollar/Node-WebDollar#20]
I installed the Node on a few units.  A) Celleron CPU, Ryzen 5, AMD i5
No Matter what processor I only get approx 500-600 H/s.
The Browser based on the Ryzen5 and I 5 get about 1800H/s

I cant find any parameter for the node to increase the "power" usage of the CPUs to get a better node perfomance

Any suggestions, please would be appreciated

**Comment by IonutAlexandruPanait** [comment]
Until this moment we didn't developed multi thread mining in CLI.

**Comment by rentodi1** [comment]
Understood.  Currently only single thread on CLI.
I Understand that I can route the Algorithm to a GPU.
I have some old low power GPU's that would do a better job than the 2 Core Celleron CPU's

Is there an option in the code I can turn on to use some of the old GPUs I have laying around.
I understand they will be controlled/lowered to a slower speed but they would do better than the Celleron CPU's

Thanks

**Comment by ibudisteanu** [comment]
@rentodi1 hi rentodl1, WebDollar uses argon2d, a memory intensive hashing function which is based on the speed of memory access. So, in reality, argon2d it is quite ASIC resistant and GPU unfriendly.  As far as I know, argon2d CLI implementation uses CPU optimization for cache memory. So, you can have some small improvements for GPU, for most, it is not that profitable.
