### ISSUE TITLE
Wrong POS hash calculation

### ISSUE THREAD

**Issue by tomkha** [WebDollar/Node-WebDollar#209]
the conversion of Number to Buffer doesn't always work the way you expect thus giving you the wrong hash

https://github.com/WebDollar/Node-WebDollar/blob/PoS/src/common/blockchain/mini-blockchain/blocks/Mini-Blockchain-Block.js#L133

```
> Buffer.from((0xAB).toString(16), 'hex').toString('hex');
'ab'
> Buffer.from((0xABC).toString(16), 'hex').toString('hex');
'ab'
> Buffer.from((0xABCD).toString(16), 'hex').toString('hex');
'abcd'
> Buffer.from((0xABCDE).toString(16), 'hex').toString('hex');
'abcd'
```

read this https://github.com/nodejs/node/issues/21242 for details

**Comment by ibudisteanu** [comment]
hex number should have an even length. The above-mentioned error looks like a javascript/node.js error only for hex strings that have an odd length.

**Comment by tomkha** [comment]
yes, you definitely have those odd length numbers in 50% cases when you divide the initial hash by the account balance
