### ISSUE TITLE
How to create a mining pool?

### ISSUE THREAD

**Issue by GYMRewards** [WebDollar/Node-WebDollar#227]
How can we create a mining pool?

**Comment by cbusuioceanu** [comment]
Hello! This is not an issue. You can create a mining pool using the following tutorial:

[https://github.com/cbusuioceanu/How-to-deploy-WebDollar-Pool/blob/master/how-to-deploy-webdollar-pool.md](url)

Thank you!

**Comment by GYMRewards** [comment]
HI, I have installed, however, when I run npm run commands to start pool I get this error after some services start. Any ideas?

 [0] ./src/common/blockchain/interface-blockchain/mining/backbone/workers/Backbone-Worker.js 4.71 kB {0} [built]
    + 1 hidden module
/home/cmilian/MiningPool1/node_modules/bindings/bindings.js:133
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /home/cmilian/MiningPool1/node_modules/argon2/build/argon2.node
 → /home/cmilian/MiningPool1/node_modules/argon2/build/Debug/argon2.node
 → /home/cmilian/MiningPool1/node_modules/argon2/build/Release/argon2.node
 → /home/cmilian/MiningPool1/node_modules/argon2/out/Debug/argon2.node
 → /home/cmilian/MiningPool1/node_modules/argon2/Debug/argon2.node
 → /home/cmilian/MiningPool1/node_modules/argon2/out/Release/argon2.node
 → /home/cmilian/MiningPool1/node_modules/argon2/Release/argon2.node
 → /home/cmilian/MiningPool1/node_modules/argon2/build/default/argon2.node
 → /home/cmilian/MiningPool1/node_modules/argon2/compiled/8.10.0/linux/x64/argon2.node
 → /home/cmilian/MiningPool1/node_modules/argon2/addon-build/release/install-root/argon2.node
 → /home/cmilian/MiningPool1/node_modules/argon2/addon-build/debug/install-root/argon2.node
 → /home/cmilian/MiningPool1/node_modules/argon2/addon-build/default/install-root/argon2.node
 → /home/cmilian/MiningPool1/node_modules/argon2/lib/binding/node-v57-linux-x64/argon2.node
    at bindings (/home/cmilian/MiningPool1/node_modules/bindings/bindings.js:124:9)
    at Object.<anonymous> (/home/cmilian/MiningPool1/node_modules/argon2/argon2.js:3:37)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (

**Comment by GYMRewards** [comment]
I was able to install, Still need to redirect to SSL.. Not working for some reason. I am stuck in Block 170, any ideas?

Block 170 successfully downloaded!
 ✘   Error including block 178 in fork  { message: 'block hash is not right',
  nonce: 5135,
  height: 178,
  myHash: '00000037a797026a063a3dabe620fc7f54dfa632380f5bbdfc4120cf0b7fc677',
  hash: 'ecbb577d736540a0de48b023fcc9facc1c4fbb6bd8aa85cb4bbbb6dfda1e3075',
  difficultyTargetPrev: '00000066e99bde973620da2e8eb4bbce474825dd6594be43cbada18fc1fb2b7a',
  serialization: '00010000000c68c0d0b7943a419882cc776df1cb4ee8775a38c7682201b9056c127b00001a13af56354d1019cb54c5822fd3ec491949ab79b1a91997f793b51a654ab8cc8206e4148dd81c9b87bd56ba7697a40d9f3670534ffc6ed29560ee41778a3faa19fa751ec51e68ca93b4d0ded9b5070502ae6b7e9cf1000000009f1d9235150f2788d7673a948205da36d53957592931211327c9a6884d66d04e0b000001731d46c131eb6dd4667a96bdc27baf9223bec72c3468dfb6ba52c460e76423a40000b30000000c68c0d0b7943a419882cc776df1cb4ee8775a38c7682201b9056c127b0000000000000000ae00000006565d30670dad5f69e16b37313699d02c57deb90be66d6f56ff1f766c000079000000faacbbf3e1a8e11655a3dc9d00d54e472d766cd91a2d84677990b3a8b100003e0000019a53e29ceab05544fead187ee8dc27632ff42c628343730467a2bd950d0000250000004afccca73bf8ad60ea7e349d1e21ed7af789e04d723a9b5fdb4b00f8770000000000000000000000140f' }
 ✘   processForksQueue returned an error { message: 'fork.includeForkBlock returned an exception',
  Exception:
   { message: 'block hash is not right',
     nonce: 5135,
     height: 178,
     myHash: '00000037a797026a063a3dabe620fc7f54dfa632380f5bbdfc4120cf0b7fc677',
     hash: 'ecbb577d736540a0de48b023fcc9facc1c4fbb6bd8aa85cb4bbbb6dfda1e3075',
     difficultyTargetPrev: '00000066e99bde973620da2e8eb4bbce474825dd6594be43cbada18fc1fb2b7a',
     serialization: '00010000000c68c0d0b7943a419882cc776df1cb4ee8775a38c7682201b9056c127b00001a13af56354d1019cb54c5822fd3ec491949ab79b1a91997f793b51a654ab8cc8206e4148dd81c9b87bd56ba7697a40d9f3670534ffc6ed29560ee41778a3faa19fa751ec51e68ca93b4d0ded9b5070502ae6b7e9cf1000000009f1d9235150f2788d7673a948205da36d53957592931211327c9a6884d66d04e0b000001731d46c131eb6dd4667a96bdc27baf9223bec72c3468dfb6ba52c460e76423a40000b30000000c68c0d0b7943a419882cc776df1cb4ee8775a38c7682201b9056c127b0000000000000000ae00000006565d30670dad5f69e16b37313699d02c57deb90be66d6f56ff1f766c000079000000faacbbf3e1a8e11655a3dc9d00d54e472d766cd91a2d84677990b3a8b100003e0000019a53e29ceab05544fead187ee8dc27632ff42c628343730467a2bd950d0000250000004afccca73bf8ad60ea7e349d1e21ed7af789e04d723a9b5fdb4b00f8770000000000000000000000140f' } }
 ⚠   BANNNNNNNNNNNNNNNNN node1.petreus.ro fork.includeForkBlock returned an exception
connecting... to:                 http://node10.petreus.ro:80
connecting... to:                 http://node8.petreus.ro:80
 ⚠   Client disconnected  node4.petreus.ro:443

**Comment by cbusuioceanu** [comment]
Yes, you need to get the blockchain backup for faster setup:

https://webdftp.vpnromania.ro/ftp/blockchainDB3.tar.gz

cd into blockchainDB3 folder, erase everything and run: wget https://webdftp.vpnromania.ro/ftp/blockchainDB3.tar.gz && tar -zxvf blockchainDB3.tar.gz && rm blockchainDB3.tar.gz

After this, start the webdollar node and use step 11 to create a Mining Pool.
