### ISSUE TITLE
Average block time is not 40s as advertised in the whitepaper

### ISSUE THREAD

**Issue by ader1990** [WebDollar/Node-WebDollar#247]
Before the PoS fork, the average block time was ~ 42s.
After the PoS fork, the average block time is ~45s.

Show me the math:
```
// Before PoS fork:
new Date("Wed, 30 Jan 2019 05:40:35 GMT")-new Date(1524743407 * 1000))/1000/(567810
// 42.4 s

// After PoS fork:
(new Date() - new Date("Wed, 30 Jan 2019 05:40:35 GMT"))/1000/(608372-567810)
// 45.3 seconds
```

**Comment by ibudisteanu** [comment]
Probably a new algorithm for difficulty adjustment must be written. This is how the difficulty is being readjusted. It looks 45s is consistent.
