### ISSUE TITLE
mine WebDollar in a Linux  terminal. rgon2-bench2 process was lost after a few hours.  pow is 0H/s

### ISSUE THREAD

**Issue by kondsXin** [WebDollar/Node-WebDollar#293]
mine WebDollar in a Linux  terminal.  but . I found out that argon2-bench2 process was lost after a few hours.  pow is 0H/s .
why argon2-bench2 process lost ? 

TOP

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
1082774 root      20   0  453448   2716   1268 S  84.1  0.0 235:45.47 argon2-bench2
2191669 konds     20   0 1184284 192124 121484 S   1.3  1.2  21:29.18 chrome
2191706 konds     20   0  558636 117640  72284 S   1.0  0.7  36:34.18 chrome
   3137 konds     20   0 2309476 192560  63828 S   0.7  1.2  17:12.53 gnome-shell
1080877 root      20   0 2177296 667544  38404 S   0.7  4.1   1:51.21 node

root@konds:~# ps auxf | grep -i argon2-bench2
root     1091216  0.0  0.0  14532   956 pts/2    S+   18:57   0:00                      \_ grep -i argon2-bench2
root     1082773  0.0  0.0   4292   748 pts/1    S+   17:36   0:00                  |               \_ /bin/sh -c  ./dist_bundle/CPU/argon2-bench2 -d 0 -c 6 -b 30000 -f ./dist_bundle/CPU/input.txt0.78002621121191450
root     1082774  291  0.0 453448  2716 pts/1    Rl+  17:36 236:53                  |                   \_ ./dist_bundle/CPU/argon2-bench2 -d 0 -c 6 -b 30000 -f ./dist_bundle/CPU/input.txt0.78002621121191450
root@konds:~#

**rgon2-bench2 process was lost after a few hours.  pow is 0H/s**

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
1008884 konds     20   0 2165720 712864 204700 S  11.0  4.4  20:32.99 chrome
2191706 konds     20   0  589664 138948  86748 S   8.0  0.9  49:19.99 chrome
   2975 konds     20   0  294360  44048  19200 S   3.3  0.3  22:22.60 Xorg
   3137 konds     20   0 2335560 219188  82692 S   3.3  1.3  22:06.67 gnome-shell
1080877 root      20   0 2203352 709044  36848 S   2.3  4.3   6:28.96 node
   3148 konds      9 -11 1702492  12708   9456 S   1.7  0.1   1:49.77 pulseaudio
2191669 konds     20   0 1574048 214316 122344 S   1.7  1.3  23:12.76 chrome
   2445 root      20   0  515168  79048  10772 S   1.0  0.5   6:17.34 pvestatd
2191714 konds     20   0  554332  91524  59540 S   1.0  0.6   2:12.71 chrome
2191906 konds     20   0  831352 138396  62180 S   0.7  0.8   7:23.14 chrome
    490 root      -2   0       0      0      0 S   0.3  0.0   0:41.77 i915/signal:0
   1736 debian-+  20   0  188340   7280   6064 S   0.3  0.0   0:26.38 transmission-da
   2453 root      20   0  517052  80816  10644 S   0.3  0.5   2:14.86 pve-firewall
1107116 root      20   0   46948   3776   3104 R   0.3  0.0   0:00.02 top
2437322 root      20   0   46916   4116   3136 S   0.3  0.0   7:44.65 top
      1 root      20   0  205060   7500   5396 S   0.0  0.0   0:28.31 systemd
      2 root      20   0       0      0      0 S   0.0  0.0   0:00.16 kthreadd

root@konds:~# ps auxf | grep -i argon2-bench2
root     1108018  0.0  0.0  14532  1028 pts/2    S+   21:10   0:00                      \_ grep -i argon2-bench2
root@konds:~#

**Comment by ADeeperBlue** [comment]
Similar issue here. Snipped from a screenlog I had running after this happened 3 times in a night. Think this might shed some light on it:

fork position 1269259 forkChainStartingPoint 0 forkChainLength 1269260
[44m[37m ℹ [0m [36m initialize fork [0m
 < fork.forkChainLength 1269260 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 1 [0m
mining....
blockchainForks Save Fork after validateFork   
blockchainForks Accountant Tree   d2030eb1eb6894503cb116a00bdd8f5f94008e8fc97c6db398f949a24856d1d5   
blockchainForks ===========================   
blockchainForks ===========================   
[44m[37m ℹ [0m [36m Creating proof:  1269259 [0m
[43m[37m ⚠ [0m [33m Saving Fork. Starting from  1269259 1269260 [0m
blockchainForks FORK STATUS SUCCESS5: true position 1269259   
blockchainForks Accountant Tree   b58e7659d67de0fb3dd8a3ec87e4a9fe6c5f20e4bfc57b9de3f66df251d37c4a   
[34mblockchainForks[0m [0m FORK SOLVER SUCCESS: true   
06e3eecabbc486e5cf080c14941d3e3cec3c5be955b1e5e3dbf95f10b23631ec ------- GOOD tx
7a3a180b9af568236219484c52cf027ecdf3cb19d835cd7ec338e7a9a2340bb9 ------- GOOD tx
844344868393dcbf61072f15a3371731a8b507cda261a7c92e778edfedf9dd1c ------- GOOD tx
[43m[37m ⚠ [0m [33m Transactions stack - 3 after removing old [0m
[41m[37m ✘ [0m [31m block  1269259  was not mined... [0m
844344868393dcbf61072f15a3371731a8b507cda261a7c92e778edfedf9dd1c WEBD$gCDUxpoV1HwINzPtfytekoiJT+PNcD$XDz$ added
7a3a180b9af568236219484c52cf027ecdf3cb19d835cd7ec338e7a9a2340bb9 WEBD$gB3H9H0MHRCx0$8wc8rREjfh5@@Uu@10cf$ added
06e3eecabbc486e5cf080c14941d3e3cec3c5be955b1e5e3dbf95f10b23631ec WEBD$gALk+$paoQjifLE@v1$onJJgeEtY31CNSX$ added
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m 0 hashes/s [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
fork position 1269260 forkChainStartingPoint 0 forkChainLength 1269261
[44m[37m ℹ [0m [36m initialize fork [0m
 < fork.forkChainLength 1269261 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 1 [0m
Block 1269260 successfully downloaded!
blockchainForks Save Fork after validateFork   
blockchainForks Accountant Tree   b58e7659d67de0fb3dd8a3ec87e4a9fe6c5f20e4bfc57b9de3f66df251d37c4a   
blockchainForks ===========================   
blockchainForks ===========================   
[44m[37m ℹ [0m [36m Creating proof:  1269260 [0m
[43m[37m ⚠ [0m [33m Saving Fork. Starting from  1269260 1269261 [0m
blockchainForks FORK STATUS SUCCESS5: true position 1269260   
blockchainForks Accountant Tree   cace6141c23d449219c6df4aa5010e0e466ebb924c941e5ffcb287c7ed0ff358   
[34mblockchainForks[0m [0m FORK SOLVER SUCCESS: true   
[41m[37m ✘ [0m [31m block  1269260  was not mined... [0m
06e3eecabbc486e5cf080c14941d3e3cec3c5be955b1e5e3dbf95f10b23631ec exception remove { message: 'This transaction was already inserted' }
[43m[37m ⚠ [0m [33m Error Including Transaction { message: 'This transaction was already inserted' } [0m
844344868393dcbf61072f15a3371731a8b507cda261a7c92e778edfedf9dd1c WEBD$gCDUxpoV1HwINzPtfytekoiJT+PNcD$XDz$
[43m[37m ⚠ [0m [33m Error Including Transaction { message: 'This transaction was already inserted' } [0m
7a3a180b9af568236219484c52cf027ecdf3cb19d835cd7ec338e7a9a2340bb9 WEBD$gB3H9H0MHRCx0$8wc8rREjfh5@@Uu@10cf$
7a3a180b9af568236219484c52cf027ecdf3cb19d835cd7ec338e7a9a2340bb9 exception remove { message: 'This transaction was already inserted' }
844344868393dcbf61072f15a3371731a8b507cda261a7c92e778edfedf9dd1c exception remove { message: 'This transaction was already inserted' }
[43m[37m ⚠ [0m [33m Transactions stack - 0 after removing old [0m
[44m[37m ℹ [0m [36m  blocks:  1269261 POW [0m
[44m[37m ℹ [0m [36m  amount mining wallet:  128353.7549   amount [0m
[44m[37m ℹ [0m [36m Exists:  YES [0m
[44m[37m ℹ [0m [36m  v:  1.212.0 [0m
[44m[37m ℹ [0m [36m up time 0 d 6 h 26 m [0m
 connected to:  5  , from:  0  web peers WEBRTC 0  Network FullNodes: 52  Network LightNodes: 520     GeoLocationContinents:  693
 browsers:  0  terminal:  5
clients:  (node4.petreus.ro)   (node5.timi.ro)   (node3.timi.ro)   (node8.webdollarminingpool.com)   (node5.webdollarminingpool.com)   
server:  
waitlist full node  52
waitlist light node  500
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m 0 hashes/s [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
fork position 1269261 forkChainStartingPoint 0 forkChainLength 1269262
[44m[37m ℹ [0m [36m initialize fork [0m
 < fork.forkChainLength 1269262 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 1 [0m
blockchainForks Save Fork after validateFork   
blockchainForks Accountant Tree   cace6141c23d449219c6df4aa5010e0e466ebb924c941e5ffcb287c7ed0ff358   
blockchainForks ===========================   
blockchainForks ===========================   
[44m[37m ℹ [0m [36m Creating proof:  1269261 [0m
[43m[37m ⚠ [0m [33m Saving Fork. Starting from  1269261 1269262 [0m
blockchainForks FORK STATUS SUCCESS5: true position 1269261   
blockchainForks Accountant Tree   2356070a0c4c63218a5a930a17b5c4a2657a6fb8f6c5ab93922ed76425768929   
[34mblockchainForks[0m [0m FORK SOLVER SUCCESS: true   
[43m[37m ⚠ [0m [33m Transactions stack - 0 after removing old [0m
[41m[37m ✘ [0m [31m block  1269261  was not mined... [0m
fork position 1269262 forkChainStartingPoint 0 forkChainLength 1269263
[44m[37m ℹ [0m [36m initialize fork [0m
 < fork.forkChainLength 1269263 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 1 [0m
blockchainForks Save Fork after validateFork   
blockchainForks Accountant Tree   2356070a0c4c63218a5a930a17b5c4a2657a6fb8f6c5ab93922ed76425768929   
blockchainForks ===========================   
blockchainForks ===========================   
[44m[37m ℹ [0m [36m Creating proof:  1269262 [0m
[43m[37m ⚠ [0m [33m Saving Fork. Starting from  1269262 1269263 [0m
blockchainForks FORK STATUS SUCCESS5: true position 1269262   
blockchainForks Accountant Tree   14f378e8c9358246cc20b25d63b7615eaa030500b73b29a0e56864f778aee2b5   
[34mblockchainForks[0m [0m FORK SOLVER SUCCESS: true   
[43m[37m ⚠ [0m [33m Transactions stack - 0 after removing old [0m
[41m[37m ✘ [0m [31m block  1269262  was not mined... [0m
newForkTip 1269263
newForkTip 1269264
fork position 1269263 forkChainStartingPoint 0 forkChainLength 1269264
[44m[37m ℹ [0m [36m initialize fork [0m
 < fork.forkChainLength 1269264 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 1 [0m
newForkTip 1269264
blockchainForks Save Fork after validateFork   
blockchainForks Accountant Tree   14f378e8c9358246cc20b25d63b7615eaa030500b73b29a0e56864f778aee2b5   
blockchainForks ===========================   
blockchainForks ===========================   
[44m[37m ℹ [0m [36m Creating proof:  1269263 [0m
[43m[37m ⚠ [0m [33m Saving Fork. Starting from  1269263 1269264 [0m
blockchainForks FORK STATUS SUCCESS5: true position 1269263   
blockchainForks Accountant Tree   58e6602fc858c27c28318250e1fa93851d2387ccb1ca7cd80d7d5640830af62b   
[34mblockchainForks[0m [0m FORK SOLVER SUCCESS: true   
[43m[37m ⚠ [0m [33m Transactions stack - 0 after removing old [0m
[41m[37m ✘ [0m [31m block  1269263  was not mined... [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m 0 hashes/s [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[34mdefault[0m [0m Restarting Worker   
[44m[37m ℹ [0m [36m  blocks:  1269264 POW [0m
[44m[37m ℹ [0m [36m  amount mining wallet:  128353.7549   amount [0m
[44m[37m ℹ [0m [36m Exists:  YES [0m
[44m[37m ℹ [0m [36m  v:  1.212.0 [0m
[44m[37m ℹ [0m [36m up time 0 d 6 h 27 m [0m
 connected to:  5  , from:  0  web peers WEBRTC 0  Network FullNodes: 52  Network LightNodes: 520     GeoLocationContinents:  693
 browsers:  0  terminal:  5
clients:  (node4.petreus.ro)   (node5.timi.ro)   (node3.timi.ro)   (node8.webdollarminingpool.com)   (node5.webdollarminingpool.com)   
server:  
waitlist full node  52
waitlist light node  500
fork position 1269264 forkChainStartingPoint 0 forkChainLength 1269265
[44m[37m ℹ [0m [36m initialize fork [0m
 < fork.forkChainLength 1269265 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 1 [0m
blockchainForks Save Fork after validateFork   
blockchainForks Accountant Tree   58e6602fc858c27c28318250e1fa93851d2387ccb1ca7cd80d7d5640830af62b   
blockchainForks ===========================   
blockchainForks ===========================   
[44m[37m ℹ [0m [36m Creating proof:  1269264 [0m
[43m[37m ⚠ [0m [33m Saving Fork. Starting from  1269264 1269265 [0m
blockchainForks FORK STATUS SUCCESS5: true position 1269264   
blockchainForks Accountant Tree   0b6b1ed6ceb84e03ce9fe901d20caf1cdb1edffd8def0c9f7742f25e9621e15d   
[34mblockchainForks[0m [0m FORK SOLVER SUCCESS: true   
[43m[37m ⚠ [0m [33m Transactions stack - 0 after removing old [0m
[41m[37m ✘ [0m [31m block  1269264  was not mined... [0m
newForkTip 1269265
newForkTip 1269265
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m 0 hashes/s [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m  blocks:  1269265 POW [0m
[44m[37m ℹ [0m [36m  amount mining wallet:  128353.7549   amount [0m
[44m[37m ℹ [0m [36m Exists:  YES [0m
[44m[37m ℹ [0m [36m  v:  1.212.0 [0m
[44m[37m ℹ [0m [36m up time 0 d 6 h 28 m [0m
 connected to:  5  , from:  0  web peers WEBRTC 0  Network FullNodes: 52  Network LightNodes: 520     GeoLocationContinents:  693
 browsers:  0  terminal:  5
clients:  (node4.petreus.ro)   (node5.timi.ro)   (node3.timi.ro)   (node8.webdollarminingpool.com)   (node5.webdollarminingpool.com)   
server:  
waitlist full node  52
waitlist light node  500
fork position 1269265 forkChainStartingPoint 0 forkChainLength 1269266
[44m[37m ℹ [0m [36m initialize fork [0m
 < fork.forkChainLength 1269266 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 1 [0m
blockchainForks Save Fork after validateFork   
blockchainForks Accountant Tree   0b6b1ed6ceb84e03ce9fe901d20caf1cdb1edffd8def0c9f7742f25e9621e15d   
blockchainForks ===========================   
blockchainForks ===========================   
[44m[37m ℹ [0m [36m Creating proof:  1269265 [0m
[43m[37m ⚠ [0m [33m Saving Fork. Starting from  1269265 1269266 [0m
blockchainForks FORK STATUS SUCCESS5: true position 1269265   
blockchainForks Accountant Tree   0007f7abe42c6eb7d8799e471e6ab3ec3f647e703272c08a4cf695b793d7e33d   
[34mblockchainForks[0m [0m FORK SOLVER SUCCESS: true   
[43m[37m ⚠ [0m [33m Transactions stack - 0 after removing old [0m
[41m[37m ✘ [0m [31m block  1269265  was not mined... [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m 0 hashes/s [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[34mdefault[0m [0m Restarting Worker   
[44m[37m ℹ [0m [36m  blocks:  1269266 POW [0m
[44m[37m ℹ [0m [36m  amount mining wallet:  128353.7549   amount [0m
[44m[37m ℹ [0m [36m Exists:  YES [0m
[44m[37m ℹ [0m [36m  v:  1.212.0 [0m
[44m[37m ℹ [0m [36m up time 0 d 6 h 28 m [0m
 connected to:  5  , from:  0  web peers WEBRTC 0  Network FullNodes: 52  Network LightNodes: 520     GeoLocationContinents:  693
 browsers:  0  terminal:  5
clients:  (node4.petreus.ro)   (node5.timi.ro)   (node3.timi.ro)   (node8.webdollarminingpool.com)   (node5.webdollarminingpool.com)   
server:  
waitlist full node  52
waitlist light node  500
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m 0 hashes/s [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
fork position 1269266 forkChainStartingPoint 0 forkChainLength 1269267
[44m[37m ℹ [0m [36m initialize fork [0m
 < fork.forkChainLength 1269267 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 1 [0m
blockchainForks Save Fork after validateFork   
blockchainForks Accountant Tree   0007f7abe42c6eb7d8799e471e6ab3ec3f647e703272c08a4cf695b793d7e33d   
blockchainForks ===========================   
blockchainForks ===========================   
[44m[37m ℹ [0m [36m Creating proof:  1269266 [0m
[43m[37m ⚠ [0m [33m Saving Fork. Starting from  1269266 1269267 [0m
blockchainForks FORK STATUS SUCCESS5: true position 1269266   
blockchainForks Accountant Tree   0a19720275c8f6f523a3ef4ee3d177082513b1790ca1edbf01d9114f02f4292d   
[34mblockchainForks[0m [0m FORK SOLVER SUCCESS: true   
[43m[37m ⚠ [0m [33m Transactions stack - 0 after removing old [0m
[41m[37m ✘ [0m [31m block  1269266  was not mined... [0m
newForkTip 1269267
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m 0 hashes/s [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
fork position 1269267 forkChainStartingPoint 0 forkChainLength 1269268
[44m[37m ℹ [0m [36m initialize fork [0m
 < fork.forkChainLength 1269268 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 1 [0m
blockchainForks Save Fork after validateFork   
blockchainForks Accountant Tree   0a19720275c8f6f523a3ef4ee3d177082513b1790ca1edbf01d9114f02f4292d   
blockchainForks ===========================   
blockchainForks ===========================   
[44m[37m ℹ [0m [36m Creating proof:  1269267 [0m
[43m[37m ⚠ [0m [33m Saving Fork. Starting from  1269267 1269268 [0m
blockchainForks FORK STATUS SUCCESS5: true position 1269267   
blockchainForks Accountant Tree   bbfd2ad330bd8f46ab7e52206baa72f505009d7125eee1ec724a15e4b967d30c   
[34mblockchainForks[0m [0m FORK SOLVER SUCCESS: true   
[43m[37m ⚠ [0m [33m Transactions stack - 0 after removing old [0m
[41m[37m ✘ [0m [31m block  1269267  was not mined... [0m
[34mdefault[0m [0m Restarting Worker   
[44m[37m ℹ [0m [36m  blocks:  1269268 POW [0m
[44m[37m ℹ [0m [36m  amount mining wallet:  128353.7549   amount [0m
[44m[37m ℹ [0m [36m Exists:  YES [0m
[44m[37m ℹ [0m [36m  v:  1.212.0 [0m
[44m[37m ℹ [0m [36m up time 0 d 6 h 29 m [0m
 connected to:  5  , from:  0  web peers WEBRTC 0  Network FullNodes: 52  Network LightNodes: 520     GeoLocationContinents:  693
 browsers:  0  terminal:  5
clients:  (node4.petreus.ro)   (node5.timi.ro)   (node3.timi.ro)   (node8.webdollarminingpool.com)   (node5.webdollarminingpool.com)   
server:  
waitlist full node  52
waitlist light node  500
fork position 1269268 forkChainStartingPoint 0 forkChainLength 1269269
[44m[37m ℹ [0m [36m initialize fork [0m
 < fork.forkChainLength 1269269 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 1 [0m
blockchainForks Save Fork after validateFork   
blockchainForks Accountant Tree   bbfd2ad330bd8f46ab7e52206baa72f505009d7125eee1ec724a15e4b967d30c   
blockchainForks ===========================   
blockchainForks ===========================   
[44m[37m ℹ [0m [36m Creating proof:  1269268 [0m
[43m[37m ⚠ [0m [33m Saving Fork. Starting from  1269268 1269269 [0m
blockchainForks FORK STATUS SUCCESS5: true position 1269268   
blockchainForks Accountant Tree   6babd90a7a119ecf1f7086b6d56bd5d31a256c3b735671136be9f4f483737afa   
[34mblockchainForks[0m [0m FORK SOLVER SUCCESS: true   
[43m[37m ⚠ [0m [33m Transactions stack - 0 after removing old [0m
[41m[37m ✘ [0m [31m block  1269268  was not mined... [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m 0 hashes/s [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m  blocks:  1269269 POW [0m
[44m[37m ℹ [0m [36m  amount mining wallet:  128353.7549   amount [0m
[44m[37m ℹ [0m [36m Exists:  YES [0m
[44m[37m ℹ [0m [36m  v:  1.212.0 [0m
[44m[37m ℹ [0m [36m up time 0 d 6 h 30 m [0m
 connected to:  5  , from:  0  web peers WEBRTC 0  Network FullNodes: 52  Network LightNodes: 520     GeoLocationContinents:  693
 browsers:  0  terminal:  5
clients:  (node4.petreus.ro)   (node5.timi.ro)   (node3.timi.ro)   (node8.webdollarminingpool.com)   (node5.webdollarminingpool.com)   
server:  
waitlist full node  52
waitlist light node  500
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m 0 hashes/s [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[44m[37m ℹ [0m [36m ------------------------------------- [0m
[34mdefault[0m [0m Restarting Worker   
fork position 1269269 forkChainStartingPoint 0 forkChainLength 1269270
[44m[37m ℹ [0m [36m initialize fork [0m
 < fork.forkChainLength 1269270 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 1 [0m
blockchainForks Save Fork after validateFork   
blockchainForks Accountant Tree   6babd90a7a119ecf1f7086b6d56bd5d31a256c3b735671136be9f4f483737afa   
blockchainForks ===========================   
blockchainForks ===========================   
[44m[37m ℹ [0m [36m Creating proof:  1269269 [0m
[43m[37m ⚠ [0m [33m Saving Fork. Starting from  1269269 1269270 [0m
blockchainForks FORK STATUS SUCCESS5: true position 1269269   
blockchainForks Accountant Tree   2e02a7494fd399bbf81d47f8150ae7e1621765bcf1543592c0a2fd977a8e2f2b   
[34mblockchainForks[0m [0m FORK SOLVER SUCCESS: true   
[43m[37m ⚠ [0m [33m Transactions stack - 0 after removing old [0m
[41m[37m ✘ [0m [31m block  1269269  was not mined... [0m
newForkTip 1269270
mining....
fork position 1269270 forkChainStartingPoint 0 forkChainLength 1269271
[44m[37m ℹ [0m [36m initialize fork [0m
newForkTip 1269271
newForkTip 1269271
 < fork.forkChainLength 1269271 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 1 [0m
Block 1269270 successfully downloaded!
blockchainForks Save Fork after validateFork   
mining....
blockchainForks Accountant Tree   2e02a7494fd399bbf81d47f8150ae7e1621765bcf1543592c0a2fd977a8e2f2b   
blockchainForks ===========================   
blockchainForks ===========================   
[44m[37m ℹ [0m [36m Creating proof:  1269270 [0m
[43m[37m ⚠ [0m [33m Saving Fork. Starting from  1269270 1269271 [0m
blockchainForks FORK STATUS SUCCESS5: true position 1269270   
blockchainForks Accountant Tree   c15ea357ba703e17ba6ba9d59929918d78a311d304b324eeeed97488a68ed5af   
[34mblockchainForks[0m [0m FORK SOLVER SUCCESS: true   
[43m[37m ⚠ [0m [33m Transactions stack - 0 after removing old [0m
newForkTip 1269272
newForkTip 1269272
[44m[37m ℹ [0m [36m  blocks:  1269271 POS [0m
[44m[37m ℹ [0m [36m  amount mining wallet:  128353.7549   amount [0m
[44m[37m ℹ [0m [36m Exists:  YES [0m
[44m[37m ℹ [0m [36m  v:  1.212.0 [0m
[44m[37m ℹ [0m [36m up time 0 d 6 h 30 m [0m
 connected to:  5  , from:  0  web peers WEBRTC 0  Network FullNodes: 52  Network LightNodes: 520     GeoLocationContinents:  693
 browsers:  0  terminal:  5
clients:  (node4.petreus.ro)   (node5.timi.ro)   (node3.timi.ro)   (node8.webdollarminingpool.com)   (node5.webdollarminingpool.com)   
server:  
waitlist full node  52
waitlist light node  500
[41m[37m ✘ [0m [31m block  1269270  was not mined... [0m
fork position 1269270 forkChainStartingPoint 0 forkChainLength 1269272
[44m[37m ℹ [0m [36m initialize fork [0m
 < fork.forkChainLength 1269272 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 2 [0m
newForkTip 1269272
mining....
Block 1269270 successfully downloaded!
[41m[37m ✘ [0m [31m Error including block 1269271 in fork  { message: 'block prevHash doesn\'t match ',
  hashPrev: '00000000000000a3edf5d845068118a1317e534eef20fcfc0b9dd538176d3755',
  blockHashPrev: '00000000000009115cbbb5b3684492989158922b99d4aa9096f0cbd7d9034525' } [0m
[41m[37m ✘ [0m [31m processForksQueue returned an error { message: 'fork.includeForkBlock returned an exception',
  Exception: 
   { message: 'block prevHash doesn\'t match ',
     hashPrev: '00000000000000a3edf5d845068118a1317e534eef20fcfc0b9dd538176d3755',
     blockHashPrev: '00000000000009115cbbb5b3684492989158922b99d4aa9096f0cbd7d9034525' } } [0m
[43m[37m ⚠ [0m [33m NEW BAN node5.webdollarminingpool.com fork.includeForkBlock returned an exception [0m
newForkTip 1269273
mining....
fork position 1269270 forkChainStartingPoint 0 forkChainLength 1269272
[44m[37m ℹ [0m [36m initialize fork [0m
 < fork.forkChainLength 1269272 fork.forkBlocks.length 0
[44m[37m ℹ [0m [36m Downloading Blocks... 2 [0m
Block 1269270 successfully downloaded!
blockchainForks Save Fork after validateFork   
blockchainForks Accountant Tree   c15ea357ba703e17ba6ba9d59929918d78a311d304b324eeeed97488a68ed5af   
blockchainForks ===========================   
blockchainForks ===========================   
[44m[37m ℹ [0m [36m Creating proof:  1269271 [0m
[43m[37m ⚠ [0m [33m Saving Fork. Starting from  1269270 1269272 [0m
blockchainForks FORK STATUS SUCCESS5: true position 1269270   
blockchainForks Accountant Tree   b3462ec33c21f652575dcac0eca002bd76d1d2bc58a42d43578e07c0ab98b4d0   
[34mblockchainForks[0m [0m FORK SOLVER SUCCESS: true   
[43m[37m ⚠ [0m [33m Transactions stack - 0 after removing old [0m
[41m[37m ✘ [0m [31m block  1269271  was not mined... [0m
fork position 1269272 forkChainStartingPoint 0 forkChainLength 1269273

**Comment by ADeeperBlue** [comment]
Happened again last night, into this morning.
For those of us who don't have a hundred million coins sitting in our wallets to make staking feasible, this is a big problem. I'd appreciate some follow-up.

**Comment by ibudisteanu** [comment]
It looks that after ` Restarting Worker   ` the argon2-bench2 worker hangs and it can not be terminated or restarted successfully.

**Comment by ADeeperBlue** [comment]
Hi Alexandru,

Thanks for the update. It doesn't always happen, though. It seems to be after specific events only. 
For example, in that screenlog I'm seeing the 'block prevHash doesn\'t match' causing fork.includeForkBlock to throw an exception; causing the processForksQueue to throw up before the argon2 worker dies and never restarts.

That sound right, or are they totally unrelated?

**Comment by ibudisteanu** [comment]
The way it is written that if argon2-bench2 crashes for some reason, won't produce hashes, it will be killed by node-webdollar and restarted. It looks it fails to do this sometimes.

**Comment by ADeeperBlue** [comment]
Understood. I suspect there's something amiss with that _particular_ unhandled exception - perhaps the empty 'catch' block in /src/common/blockchain/interface-blockchain/protocol/Interface-Blockchain-Protocol-Forks-Manager.js is to blame? [Line 141, processForksQueue()]

**Comment by ADeeperBlue** [comment]
Happened again, this time it stopped mining and did a resync, totally unprompted.

`agent basic synchronization`
`################### RESYNCHRONIZATION STARTED ##########`
`Mining Stopped`
`Stop Mining!`
`KILL!!`
`startAgent has started`
`Synchronization done FAILED`
[libargon2 benchmark results...]
`done`
[Blank info line]
`block 1271594  was not mined...`
`Synchronization done`
`Blockchain Ready to Mine`

Hashrate drops to zero thereafter.

**Comment by ibudisteanu** [comment]
WebDollar will be merged into POS100%
