### ISSUE TITLE
Creating a new mining pool uses an inactive domain

### ISSUE THREAD

**Issue by TreeOfSelf** [WebDollar/Node-WebDollar#363]
So, it looks like at one point webdollar.ddns.net:9094 was running, and that is where new mining pools default to. Looks like it hasn't been running for years though, and this isn't mentioned at all in the documentation or fixed. Just curious how I can get around this?

**Comment by TreeOfSelf** [comment]
So, nothing? If this is a dead project please just let me know so I don't waste anymore time with it.

**Comment by TreeOfSelf** [comment]
lmao, so you close my issue and don't even answer the question. So, basically creating a new pool isn't possible right now and is broken?

**Comment by ibudisteanu** [comment]
You can create your own pool. webdollar.ddns.net:9094 was a mining pool launched by me in 2018. Later I was no longer interested to run my own pool as we had 9 pools at that time. Right now we have some pools online as well 
![image](https://user-images.githubusercontent.com/17750489/160446671-7f2cf84b-c90b-41d0-8e21-6268185c3d90.png)

**Comment by ibudisteanu** [comment]
The default domain is as a sample name to notify people that they need a domain or a fixed IP address. You just have to change the default name with the one you provide...
