### ISSUE TITLE
No incoming connections for terminal nodes created after 1.133.1 commit 644b3a3

### ISSUE THREAD

**Issue by WhistleWhileYouWork** [WebDollar/Node-WebDollar#38]
Changes in commit 644b3a3 cause new nodes on previously unused ports to not receive any incoming connections. Nodes using commit 94e7fb0 and prior versions do receive incoming connections. I have tested a node on each commit and 94e7fb0 has 10 connections to other nodes but 0 connections from other nodes after 8 hours. All versions since commit 94e7fb0 exhibit this behavior.

It is important to understand that any node that has recently run a version prior to 94e7fb0 and since upgraded to a newer version will have incoming connections because it's address has already propagated from the working version. But a new node on a new port with version 94e7fb0 or later will not have incoming connections. Nodes listed on the fallback list are an exception since they are discovered by default.

To reproduce:
npm install using commit 644b3a3. Start mining using a previously unused port (do NOT use a standard port: 80, 443 etc).

**Comment by WhistleWhileYouWork** [comment]
I am now finally getting incoming tcp connections to the node running the 94e7fb0 commit. However, my other nodes have been running 1.133.6 and 1.133.7 since they were released and they still have 0 incoming tcp connections. I realized I was still using: MAXIMUM_CONNECTIONS_FROM_BROWSER=20 MAXIMUM_CONNECTIONS_FROM_TERMINAL=10 from previous attempts to minimize the impact to my router. This may have has an influence on connectivity. I will try other versions without MAX_CONNECTIONS settings.

**Comment by ibudisteanu** [comment]
You can choose the parameters that work the best for you. The main idea is that as a full node you should create a TCP server to allow other nodes to connect to you.

**Comment by WhistleWhileYouWork** [comment]
OK, without setting any environment variables, I was able to get 1.133.6 to accept connections after several hours, but after 18 hours on a 1.133.7 node and after 12 hours, on three 1.133.8 nodes, I have not received any incoming TCP connections (monitored through my router) and 'servers' in console output shows 0.

In older versions (1.133 or before), incoming connections would be established in less than an hour.

**Comment by ibudisteanu** [comment]
Yesterday, I saw that by default MAXIMUM_CONNECTIONS_FROM_BROWSER was undefined. I fixed it in these new commits. Probably it will fix your issue too

**Comment by cbusuioceanu** [comment]
@WhistleWhileYouWork is this issue still present? If not please confirm. Thx

**Comment by WhistleWhileYouWork** [comment]
@cbusuioceanu I have to set up my SSL certificate to test this again. Might take a few days.

**Comment by cbusuioceanu** [comment]
You can use start-node-letsencrypt.sh it will take care of everything in less that one minute - make sure you don't have apache or anything else using port 80.

**Comment by WhistleWhileYouWork** [comment]
Very useful tool! Thanks for writing it. I needed to add the certbot repository to apt per their instructions: https://certbot.eff.org/lets-encrypt/ubuntuxenial-other

$ sudo apt-get update
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository ppa:certbot/certbot
$ sudo apt-get update
$ sudo apt-get install certbot

**Comment by cbusuioceanu** [comment]
Thank you! If you had time to test, was the issue still present?

Note: adding the PPA repository may be a security issue.

certbot is already in the main repository

> Security

> PPAs have not undergone the same process of validation as regular ubuntu packages. End users install PPAs at their own risk. Although each key is cryptographically signed, in order to confirm an uploader, keys are not matched to specific individuals, except via their "launchpad" accounts.

> Subsequently, installing a PPA should be considered to be a low-security alternative as compared to the main repository, but marginally higher security than simply installing software at random from the internet. As part of adding a PPA, you trust the developer to not only install packages, but also to allow them to provide ongoing updates.

**Comment by cbusuioceanu** [comment]
@WhistleWhileYouWork yes, you were right. I don't understand why ubuntu don't have certbot in their main repo. I added the certbot ppa repo to the script.
