### ISSUE TITLE
Importing address function is browser dependent

### ISSUE THREAD

**Issue by cristiwn** [WebDollar/Node-WebDollar#6]
Test steps:

1
 open http://webdollar.io/ in Firefox 58.0.2 (64-bit)
 open http://webdollar.io/ in Google Chrome 64.0.3282.140 (64-bit)
2 
 Wait 1-5 minutes in order to mine a few units.
3
 Check each wallet's amount.
4
 Use download wallet functions to save each browser's wallet(walletFirefox and walletChrome) 
 Delete wallets from each browser.
5
 Import walletFirefox in Firefox
 Import walletChrome in Google Chrome
6
 Check each wallet's amount.
 Expected : same as step 3.
 Obtained: same as step 3.
7
 Stop mining to wallets tested
8
 Import walletFirefox in Google Chrome
 Import walletChrome in Firefox
9
 Check each wallet's amount.
 Expected : same as step 3.
 Obtained: zero(0)   !!!

It looks that the wallet is browser dependent. When imported in same browser from where it was created, the synchronizing with the network is done. 
When changing browser for a wallet, the amount of units is set to zero.  It's just like the imported address is a new one. May be a formatting issue with the address, I think. I haven't checked the code, is just an assumption.

**Comment by cristiwn** [comment]
No issue, Chrome not sincronized.

**Comment by ibudisteanu** [comment]
There is an open issue, that in case you have a proxy/Firewall that blocks all other ports except 80 (http), the consensus is not established. 

I will work on this

**Comment by ibudisteanu** [comment]
I solved your problem. It was an issue when your devices were blocked by a firewall/antivirus except the port 80 for surfing the internet. Now, we have at least one node on port 80 for socket.io
