### ISSUE TITLE
Node Private API is not working

### ISSUE THREAD

**Issue by tomkha** [WebDollar/Node-WebDollar#74]
Changes made with [this commit](https://github.com/WebDollar/Node-WebDollar/commit/f1bf1f821bc97867ed16bd127cfffc2a91caccee) imply that named path parameters are always used:

https://github.com/WebDollar/Node-WebDollar/blob/MiningPools/src/node/sockets/node-server/express/Node-Express.js#L197

on the other hand private API routing does not defined any named parameters:

https://github.com/WebDollar/Node-WebDollar/blob/MiningPools/src/node/sockets/node-server/API-router/Node-API-Router.js#L23

so there is no way to pass URL parameters to the private API methods which makes them unusable.

P.S. Just my five cents - REST methods like wallets/create-transaction or wallets/import are typically called using POST.

**Comment by morion4000** [comment]
`P.S. Just my five cents - REST methods like wallets/create-transaction or wallets/import are typically called using POST.` - Agree, I will keep this in mind when doing a future update
